name: "WWA Wing: Create New Version Pull Request"

on:
  # WWAWing/WWAWing リポジトリのリリース完了時に飛ぶ 'wwa-wing-release' dispatch で動きます
  repository_dispatch:
    types: [wwa-wing-release]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Configure"
        run: |
          git config user.name "[Automatically Released] Matsuyuki"
          git config user.email "matsuyuki.eca@gmail.com"
          echo "WWA_WING_VERSION=${{ github.event.client_payload.targetVersion }}" >> "$GITHUB_ENV"
          echo "BRANCH_NAME=feature/update-to-v${{ github.event.client_payload.targetVersion }}" >> "$GITHUB_ENV"

      - name: "Install"
        run: "npm i"

      - name: "Append the latest version to releases.json"
        run:  "npx ts-node ./scripts/append-version.ts ${{ env.WWA_WING_VERSION }}"

      - name: "Commit"
        run: |
          git add -u
          git checkout -b "${{ env.BRANCH_NAME }}"
          git commit -m "feat(releases): Release v${{ env.WWA_WING_VERSION }}"

      - name: "Pull request"
        run:  "npx ts-node ./scripts/creaate-pr"
